### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by Behazy** [decisionforce/CoPO#11]
(copo) user@user-virtual-machine:~/CoPO/copo_code/copo$ python vis.py 
Successfully registered the following environments: ['MetaDrive-validation-v0', 'MetaDrive-10env-v0', 'MetaDrive-100envs-v0', 'MetaDrive-1000envs-v0', 'SafeMetaDrive-validation-v0', 'SafeMetaDrive-10env-v0', 'SafeMetaDrive-100envs-v0', 'SafeMetaDrive-1000envs-v0', 'MARLTollgate-v0', 'MARLBottleneck-v0', 'MARLRoundabout-v0', 'MARLIntersection-v0', 'MARLParkingLot-v0', 'MARLMetaDrive-v0'].
Traceback (most recent call last):
  File "vis.py", line 49, in <module>
    action = policy_function(o, d)
  File "/home/user/CoPO/copo_code/copo/eval/get_policy_function.py", line 153, in __call__
    actions = self.policy(obs_to_be_eval)
TypeError: 'str' object is not callable

**Comment by Behazy** [comment]
Sorry,I'll reinstall it according to the tutorial first.

**Comment by pengzhenghao** [comment]
It seems like a bug I introduced recently. Sorry for that. I will fix it soon!
