### ISSUE TITLE
Code implementation

### ISSUE THREAD

**Issue by Lucky-Lance** [decisionforce/CoPO#15]
Hello, your code is implemented with *ray* and *tf*. Can you please provide a copy with *pytorch*? Thanks.

**Comment by pengzhenghao** [comment]
Hi @Lucky-Lance , I am preparing a torch + RLLib version of CoPO and will release soon (probably next week).

**Comment by pengzhenghao** [comment]
Just for your information, the torch version of CoPO is implemented here:  https://github.com/decisionforce/CoPO/tree/main/copo_code/copo/torch_copo

with ray==2.2.0
