### ISSUE TITLE
Running on a remote server?

### ISSUE THREAD

**Issue by 6Lackiu** [decisionforce/CoPO#18]
Hello, I want to run the visualization program `python vis.py` on a remote server, but the following problem occurs.
![image](https://user-images.githubusercontent.com/52661423/171645217-825a13c4-f71d-415c-85a2-c36258460353.png)
Can the visualization program be started on a remote server?

**Comment by pengzhenghao** [comment]
Sorry for late reply, I misconfigure my email setting.

I think running the Pygame renderer in remote server should be OK. But native MetaDrive renderer will cause some errors.

I saw you closed the issue, anything I can help you at this times step? Thanks!

**Comment by 6Lackiu** [comment]
> Sorry for late reply, I misconfigure my email setting.
> 
> I think running the Pygame renderer in remote server should be OK. But native MetaDrive renderer will cause some errors.
> 
> I saw you closed the issue, anything I can help you at this times step? Thanks!

It's been fine, thanks! I have successfully run CoPO on my local machine, great project!
