### ISSUE TITLE
Eval error

### ISSUE THREAD

**Issue by 6Lackiu** [decisionforce/CoPO#19]
Hi! I got this error when trying to run `evaluate_population.py`, how does this happen?
![eval error](https://user-images.githubusercontent.com/52661423/174473171-acfd5150-1e67-463e-9f39-6e4dc5190845.png)

**Comment by 6Lackiu** [comment]
Thanks!@pengzhenghao  I have successfully run `evaluate_population.py` and also get the corresponding .csv file which is useful for research.
I just want to ask, does the warning that appear have any effect on the final result?
![image](https://user-images.githubusercontent.com/52661423/175498839-099f3424-5362-4a34-a246-a908f303fb0f.png)
Also, looking forward to your updates to the official eval script and DrawEvalResult script!
Thanks a lot for your reply!

**Comment by pengzhenghao** [comment]
The warnings here have no effect on the result at all and you can just ignore them.
