### ISSUE TITLE
Some Visualization Issues

### ISSUE THREAD

**Issue by 6Lackiu** [decisionforce/CoPO#22]
Hello, I am very interested in the CoPO project! 
But at the moment I have some problems, I hope you can clear my confusion, thanks!
1. The following error is prompted when running `vis_from_checkpoint.py`. 
![vis_error](https://user-images.githubusercontent.com/52661423/175765662-52e1c360-9ce2-4587-a6fd-0c12e3d0d0e9.png)
My path points to checkpoint-480 as shown. What is the cause of the error? Is it the wrong way to run the script?
![ckpt](https://user-images.githubusercontent.com/52661423/175765964-2aeb1c14-1d2a-4437-bc02-9427ec8cf6cd.png)

2. I don't understand how the .npz file in the best_checkpoints folder is generated? 
![npz](https://user-images.githubusercontent.com/52661423/175766070-0f8f1cdb-7ed5-4656-bd50-ebeded6c533f.png)

3. You declare checkpoint read type as checkpoint-xxx in `vis_from_checkpoint.py`.
![image](https://user-images.githubusercontent.com/52661423/175765718-6063c992-1fb1-4311-b4db-ba38542963ce.png)
But declare checkpoint_name is like: {ALGO}_ {ENV} _{INDEX}.npz in `get_policy_function.py`. 
![image](https://user-images.githubusercontent.com/52661423/175765764-578d5f6c-ce8c-4773-a28c-135697e670fb.png)
Which way should I follow? Do I need to convert checkpoint-xxx files to npz files? How to convert it?

4. What does "Note that if you are restoring CoPO checkpoint, you need to implement appropriate wrapper to encode the LCF into the observation and feed them to the neural network." in `vis_from_checkpoint.py` mean?
![image](https://user-images.githubusercontent.com/52661423/175765834-f6f6fd9a-1b44-4afd-9808-9f940024f3d8.png)

5. How is the following visualization made? The vehicle trajectory and collision location are visually displayed, which is great!
![image](https://user-images.githubusercontent.com/52661423/175765852-3dbbb7a6-4268-457b-861a-e4c023087e23.png)

Very much looking forward to your reply! Thank you for taking the time to answer these questions!

**Comment by 6Lackiu** [comment]
@pengzhenghao Still looking forward to your reply! Thanks!

**Comment by pengzhenghao** [comment]
Hi @6Lackiu 

I encountered your problem 1 when I am revisiting my code. A quick fix is to modify the `layer_name_suffix` when defining policy function:

<img width="905" alt="image" src="https://user-images.githubusercontent.com/22206995/177952681-9bdc2f25-a102-4e95-bf00-8892155eaac0.png">

**Comment by 6Lackiu** [comment]
> Hi @6Lackiu
> 
> I encountered your problem 1 when I am revisiting my code. A quick fix is to modify the `layer_name_suffix` when defining policy function:
> 
> <img alt="image" width="905" src="https://user-images.githubusercontent.com/22206995/177952681-9bdc2f25-a102-4e95-bf00-8892155eaac0.png">


@pengzhenghao Thank you very much! Your answer helped me a lot!

Also, I tried the fix you said.

![image](https://user-images.githubusercontent.com/52661423/178002222-51e1e701-b729-4537-bcbc-1934535c1d42.png)

But still got the following error.
![error](https://user-images.githubusercontent.com/52661423/178000451-a95600f0-139f-4159-a279-67bce1995094.png)

My checkpoint path is `ckpt_path = "/home/lxy/CoPO/copo_code/copo/myTest/interCopo0624/CoPO_CCMultiAgentIntersectionEnv_7653e_00000_0_start_seed=5000,seed=0,use_centralized_critic=False,use_distributional_svo=True_2022-06-24_11-19-30/checkpoint_625/checkpoint-625"
`

I haven't modified the core part of CoPO yet, there shouldn't be a dimensional error. Why is this?

**Comment by pengzhenghao** [comment]
This assertion error shows that the input observation is not correct.

91 is the shape of your obs and 92 is what CoPO network expecting.

Obviously, this is because you don't add LCF to the last dimension of the observation.

Try this:

> For your question 4, as you might know, LCF should serve as the last dimension in the observation. However, the environment in vis.py will only return the raw observation. Therefore, we need to manually insert the LCF and append it to the observation to create an obs that fits into CoPO's policy network. You can hack like new_obs = np.concatenate([old_obs, [0.5]]) so that you tell CoPO agent that we are using LCF=0.
>
>A note here is that LCF should be scale to [0, 1.0] instead of [-1, 1] in the observation. Please refer to the code of my CoPO agents.

**Comment by 6Lackiu** [comment]
@pengzhenghao Thank you for your clear answer!

I still have some confusion, since checkpoint-xxx can be converted to .npz file, what is the difference between vis.py and vis_from_checkpoint.py? They all work by reading in .npz files.

In addition, run evaluate_population.py to get the .csv file. How to judge which checkpoint has the best effect through the .csv file, so as to store it in the best_checkpoints folder.

Or is there something wrong with my understanding?

Looking forward to your reply!

**Comment by pengzhenghao** [comment]
Hi @6Lackiu 

Since I am preparing to release evaluation result, I have refactored the evaluation script but not yet merge.

https://github.com/decisionforce/CoPO/pull/24

You can take a look on this PR, where the `eval.py` script is the script that I want every user can use it to evaluate **their own population from RLLib raw result** without npz file.

You can add me WeChat so we can discuss more and I am waiting for your email for days..

**Comment by pengzhenghao** [comment]
Just FYI, I finished benchmarking the results of various MARL algorithms in MetaDrive MARL environments. Please kindly refer to this page:  https://github.com/metadriverse/metadrive-benchmark/tree/main/MARL

And I also upload latest trained models so you can run it to visualize the behaviors.  https://github.com/decisionforce/CoPO#visualization

Thanks!
