### ISSUE TITLE
When training multi-agent(train_all_copo_dist.py), observation type is not a Dictionary but a Box

### ISSUE THREAD

**Issue by hyoonsoo** [decisionforce/CoPO#26]
When execute 'train_all_copo_dist.py', I was watching the process of generating train data.
in this project,  because it is multi-agent observation, I think observation should be gym.Dict. (as wrote in ,annotation: 
'metadrive/manager/agent_manager.py'  )
but I checked obs_space generated in Box type.
and It was executed normally.(no errors)
![image](https://user-images.githubusercontent.com/87927823/195091143-0377bbb1-1556-4fae-ad39-a6143398d517.png)

How can I fix this problem? Or is this not a problem?

**Comment by pengzhenghao** [comment]
![image](https://user-images.githubusercontent.com/22206995/195687132-6dcc66f4-5f78-4447-9721-260318c12dba.png)

As you can see, the obs space here are single agent's obs space, so it's Box naturally.

**Comment by hyoonsoo** [comment]
Thank you for your kind answer.
I got mixed up.
