### ISSUE TITLE
dos CoPO use only one policy? or many policies for each agent?

### ISSUE THREAD

**Issue by hyoonsoo** [decisionforce/CoPO#30]
****I am asking because I am confused whether 'CoPO' trains several policies or not. I understood that It would use one policy per agent, is this right?

**Comment by pengzhenghao** [comment]
CoPO shares one policy for all agents. This is because the number of agents in the environment is consistently changing and it is impossible to train policy for each active vehicle.

**Comment by hyoonsoo** [comment]
thanks a lot!!!
I have more questions, and I would really appreciate your help.
I want to train some agents not to follow CoPO's policy, so can you tell me which part of the code I need to modify?

**Comment by pengzhenghao** [comment]
Changing part of agents to follow other policy is possible. Change the training config of RLlib in this item: `config["multiagent"]` but this is a little bit complicated. You might wish to refer to RLLib's docs to see the concepts of "policy" and "agent".

Basically, we bind all agents to the policy with named "default", which is a shared CoPO policy. But it is possible for you to, e.g., bind all agent with odd agent index "agent1, agent3, ..." to be controlled by other policy like Independent PPO.
