### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by Mming11** [decisionforce/CoPO#31]
When i have my checkpoint folder , how can i visualize it . When i run [vis_from_checkpoint.py] directly, there is something wrong with it .I know checkpoint need to be processed but i don not know how to do. I'm so sorry for my stupid... Hope you can give me hints in detail or examples. Thanks a lot. ToT

**Comment by pengzhenghao** [comment]
Please take a look on this file:

https://github.com/decisionforce/CoPO/blob/18e97ae30beccd393b580281f509d8e7ed561126/copo_code/copo/new_vis.py

We update the visualization script so that it can read RLLib checkpoints directly (without converting weight to numpy first).

**Comment by Mming11** [comment]
Thank you. I'll try it this afternoon.

**Comment by Mming11** [comment]
> Please take a look on this file:
> 
> https://github.com/decisionforce/CoPO/blob/18e97ae30beccd393b580281f509d8e7ed561126/copo_code/copo/new_vis.py
> 
> We update the visualization script so that it can read RLLib checkpoints directly (without converting weight to numpy first).

when i run new_vis.py , i meet an error.
![1](https://user-images.githubusercontent.com/80202433/215241223-379ba81d-6557-4a07-b136-533d728e46d6.jpg)
ToT
