### ISSUE TITLE
Does copo use "traffic light" and "communication" information as observation?

### ISSUE THREAD

**Issue by iamrice** [decisionforce/CoPO#36]

**Comment by iamrice** [comment]
I mean the algorithm version in the paper.

**Comment by pengzhenghao** [comment]
No. They are completely useless in previous work.

**Comment by iamrice** [comment]
Thanks.

**Comment by iamrice** [comment]
@pengzhenghao Hi, I found that the experiment result of the parking lot in the paper is different from that in 《MetaDrive: Composing Diverse Driving Scenarios for Generalizable Reinforcement Learning》

![image](https://user-images.githubusercontent.com/46922809/227410451-f0c7d965-2ebd-4687-986c-385ef93416bb.png)

![image](https://user-images.githubusercontent.com/46922809/227410747-888bf733-9e68-48bf-85b8-43e7b4f91280.png)

I notice that the paper of metadrive claims "the result is based on MetaDrive 0.2.5 and is different to previous paper [35] due to updates in MetaDrive.". But I am still curious what makes them differ so much?

Actually, I tried to implement ppo for metadrive, but i got a very poor success rate in parking lot. The success rate is about 0~0.2. 

Thanks.

**Comment by pengzhenghao** [comment]
>  i got a very poor success rate in parking lot. The success rate is about 0~0.2.

That's align with our benchmark result with 0.2.5:  https://github.com/decisionforce/CoPO/tree/main/benchmarks/MetaDrive-0.2.5

I probably will run new benchmark experiments to see the performance. My suggestion is, you can stick with the MetaDrive version you have and run fair comparisions between different algorithms.
