### ISSUE TITLE
Run without reaction (but no error)

### ISSUE THREAD

**Issue by SchunWen** [decisionforce/CoPO#40]
The code running on the server keeps showing this message without progress。Hope to get answers, thank you
![PR2 NSR749 07C~( )2 1CK](https://github.com/decisionforce/CoPO/assets/107091945/40fabb56-9a0e-4bc0-b3e2-3e50835be8a5)

**Comment by pengzhenghao** [comment]
I don't think that's a bug. Any more information you could provide?
